name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch:      # Allow manual trigger
  push:                  # Also run on push (for testing)
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner@v1
        with:
          scan-args: --recursive ./

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install and run Semgrep
        run: |
          pip install semgrep
          semgrep scan --config auto
        continue-on-error: true 