name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch:      # Allow manual trigger
  push:                  # Also run on push (for testing)
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@main
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install and run Semgrep
        run: |
          pip install semgrep
          semgrep scan --config "p/java" . || true
        continue-on-error: true

      - name: Upload Security Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif 