name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne à minuit
  workflow_dispatch:      # Permet l'exécution manuelle

jobs:
  DependenciesAnalysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@main
        
      - name: Upload Security Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv-scanner-results.sarif

  SourceCodeAnalysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep Analysis
        run: semgrep scan --config "p/java" .
        
      - name: Upload Security Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif 